using System.IO;
using System.Xml.Serialization;
using System.Collections.Generic;

// Address class (nested collection object)
public class Address
{
    public string City { get; set; }
    public string State { get; set; }
}
public class Student2
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int Age { get; set; }
    // Collection of simple types
    public List<string> Subjects { get; set; }

    // Collection of complex objects
    public List<Address> Addresses { get; set; }

    // Array collection
    public string[] Skills { get; set; }
    public int[] Marks{get; set;}
}

public class XmlConverter
{
    public static string ConvertToXml<T>(T obj)
    {
        // Creates an object that knows how to convert type T into XML.
        XmlSerializer serializer = new XmlSerializer(typeof(T));

        // StringWriter stores text in memory (RAM), not in a file.
        // XML generated by XmlSerializer is written into this object.
        using StringWriter writer = new StringWriter();

        // obj → converted into XML
        // XML is written into writer
        serializer.Serialize(writer, obj);

        // Converts the in-memory XML text into a string
        return writer.ToString();
    }
}

public class ObjectToXML
{
    public static void Run()
    {
        Student2 student = new Student2
        {
            Id = 1,
            Name = "Krishna",
            Age = 22,

            Subjects = new List<string>
            {
                "Maths",
                "Computer Science",
                "Physics"
            },

            Skills = new string[]
            {
                "C#",
                ".NET",
                "SQL"
            },
            Marks = new int[]
            {
                25,
                49,
                98,
            },

            Addresses = new List<Address>
            {
                new Address { City = "Delhi", State = "Delhi" },
                new Address { City = "Jaipur", State = "Rajasthan" }
            }
        };

        string xmlData = XmlConverter.ConvertToXml(student);
        Console.WriteLine(xmlData);
    }
}